"""
报告生成器
生成 HTML 测试报告 + 导出 JSON 原始数据
"""

import os
import json
import statistics
from datetime import datetime
from typing import Dict, Any, List


class ReportGenerator:
    def __init__(self, output_dir=None):
        self.output_dir = output_dir or os.path.join(
            os.path.dirname(__file__), "..", "..", "reports"
        )
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_html_report(self, track_results, raw_data=None, run_id=None):
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        track_html = ""
        for track, result in track_results.items():
            if result.get("status") == "skipped":
                track_html += self._skipped_section(track, result)
                continue
            track_html += self._track_section(
                track, result,
                run_id=result.get("run_id"),
                models_data=result.get("results", {}),
            )

        css = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 20px; background: #f7f9fb; color: #333; font-size: 14px; line-height: 1.7; }
h1 { color: #1565c0; border-bottom: 3px solid #1565c0; padding-bottom: 10px; }
h2 { color: #0d47a1; border-left: 4px solid #0d47a1; padding-left: 12px; }
h4 { color: #424242; margin-top: 12px; }
table { border-collapse: collapse; width: 100%; margin: 10px 0 20px; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
th, td { border: 1px solid #e0e0e0; padding: 6px 10px; text-align: left; font-size: 13px; }
th { background: #1976d2; color: #fff; }
tr:nth-child(even) { background: #f5f8fc; }
.passed { color: #2e7d32; font-weight: bold; }
.failed { color: #c62828; font-weight: bold; }
.pending { color: #ef6c00; font-weight: bold; }
.skipped { color: #757575; font-weight: bold; }
.header { background: linear-gradient(135deg, #1565c0, #0d47a1); color: #fff; padding: 18px 24px; border-radius: 8px; margin-bottom: 20px; }
.card { background: #fff; border-radius: 8px; padding: 16px; margin: 12px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
.track-box { border: 1px solid #bbdefb; border-radius: 8px; margin: 15px 0; overflow: hidden; }
.track-header { background: #e3f2fd; padding: 10px 16px; font-weight: bold; }
.stat { display: inline-block; margin: 4px 10px; padding: 3px 8px; background: #e8eaf6; border-radius: 4px; font-size: 12px; }
footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; padding: 20px; border-top: 1px solid #eee; }
progress { width: 100px; height: 14px; }
"""

        html_lines = [
            '<!DOCTYPE html>',
            '<html lang="zh-CN">',
            '<head><meta charset="UTF-8"><title>北京移动 Token 测试报告</title>',
            '<style>' + css + '</style></head>',
            '<body>',
            '<div class="header">',
            '<h1>北京移动 Token 模型聚合平台 - 模拟测试报告</h1>',
            '<p>生成时间: %s | 运行ID: %s | 环境: 本地模拟</p>' % (now, run_id or "N/A"),
            '</div>',
            track_html,
            '<footer>',
            '<p>Generated by AoYee Test Platform v1.0.0</p>',
            '<p>对标北京移动 2026年 Token 模型聚合平台合作伙伴征集文件</p>',
            '</footer>',
            '</body></html>',
        ]

        report_file = os.path.join(
            self.output_dir,
            "test-report-%s.html" % (run_id or datetime.now().strftime("%Y%m%d_%H%M%S"))
        )
        with open(report_file, "w", encoding="utf-8") as f:
            f.write("\n".join(html_lines))
        return report_file

    def _skipped_section(self, track, result):
        msg = result.get("message", "跳过")
        return '<div class="track-box"><div class="track-header">SKIP: %s - %s</div></div>' % (track, msg)

    def _track_section(self, track, result, run_id=None, models_data=None):
        LABELS = {
            "text": "[1] 文本大模型服务",
            "image": "[2] 图像生成大模型服务",
            "video": "[3] 视频生成大模型服务",
            "audio": "[4] 语音与音频类服务",
            "multimodal": "[5] 多模态理解服务",
        }
        label = LABELS.get(track, track)
        models_html = ""
        if models_data:
            for mid, results in models_data.items():
                models_html += self._model_card(mid, results)

        return '<div class="track-box">' \
               '<div class="track-header">' + label + '</div>' \
               '<div style="padding: 16px;">' \
               '<p>RunID: %s</p>' % (run_id or "N/A") \
               + models_html + '</div></div>'

    def _model_card(self, model_id, results):
        if not results:
            return '<div class="card"><h4>%s</h4><p style="color:#999">无数据</p></div>' % model_id

        total = len(results)
        success = sum(1 for r in results if isinstance(r, dict) and r.get("status") == "success")
        error = sum(1 for r in results if isinstance(r, dict) and r.get("status") in ("error", "timeout"))
        skipped = sum(1 for r in results if isinstance(r, dict) and r.get("status") == "skipped")

        ttfts = []
        speeds = []
        tokens = []
        for r in results:
            if not isinstance(r, dict):
                continue
            tt = r.get("ttft", 0) or r.get("ttft_ms", 0)
            if isinstance(tt, (int, float)) and tt > 0:
                ttfts.append(tt if tt > 1 else tt * 1000 / 1000)  # normalize
            s = r.get("speed", 0) or r.get("avg_speed_toks", 0)
            if isinstance(s, (int, float)) and s > 0:
                speeds.append(s)
            tok = r.get("output_tokens", 0) or r.get("p70_speed_toks", 0)
            if isinstance(tok, (int, float)):
                tokens.append(tok)

        ttft_list = [r.get("avg_ttft_ms", 0) for r in results if isinstance(r, dict) and r.get("avg_ttft_ms", 0) > 0]
        if not ttft_list:
            ttft_list = [r.get("ttft", 0) * 1000 for r in results if isinstance(r, dict) and r.get("ttft", 0) > 0]

        ttft_avg = "%.0f ms" % (statistics.mean(ttft_list)) if ttft_list else "-"
        ttft_p50 = "%.0f ms" % (statistics.median(ttft_list)) if ttft_list else "-"
        speed_avg = "%.2f tok/s" % (statistics.mean(speeds)) if speeds else "-"
        speed_p70 = "-"
        if len(speeds) > 1:
            sp = sorted(speeds)
            idx = min(int(len(sp) * 0.7), len(sp) - 1)
            speed_p70 = "%.2f tok/s" % sp[idx]

        table_body = ""
        for i, r in enumerate(results[:50]):
            if not isinstance(r, dict):
                continue
            status = r.get("status", "-")
            cls_map = {"success": "passed", "error": "failed", "timeout": "failed", "skipped": "skipped"}
            sc = cls_map.get(status, "pending")

            avg_ttft = r.get("avg_ttft_ms", 0) or 0
            if avg_ttft == 0:
                ttft_raw = r.get("ttft", 0)
                avg_ttft = ttft_raw * 1000 if ttft_raw > 0 else 0

            durations_s = r.get("total_duration", 0)
            tb_ft = "%.0f ms" % avg_ttft if avg_ttft > 0 else "-"

            spd = r.get("speed", 0) or r.get("avg_speed_toks", 0)
            spd_str = "%.1f tok/s" % spd if spd > 0 else "-"

            tok = r.get("output_tokens", 0) or r.get("p70_speed_toks", 0)
            if isinstance(tok, (int, float)) and tok == 0:
                tok = "-"

            t_case = str(r.get("test_case_id", "-"))[:25]

            table_body += '<tr>'
            table_body += '<td>%d</td>' % (i + 1)
            table_body += '<td>%s</td>' % t_case
            table_body += '<td class="%s">%s</td>' % (sc, status)
            table_body += '<td>%s</td>' % tb_ft
            table_body += '<td>%.2fs</td>' % durations_s
            table_body += '<td>%s</td>' % spd_str
            table_body += '<td>%s</td>' % str(tok)
            table_body += '</tr>\n'

        return '<div class="card">' \
               '<h4>%s</h4>' % model_id \
               + '<div>' \
               + '<span class="stat">总数: %d</span>' % total \
               + '<span class="stat" style="color:#2e7d32">OK: %d</span>' % success \
               + '<span class="stat" style="color:#c62828">ERR: %d</span>' % error \
               + '<span class="stat" style="color:#757575">SKIP: %d</span>' % skipped \
               + '<span class="stat">均TTFT: %s</span>' % ttft_avg \
               + '<span class="stat">P50 TTFT: %s</span>' % ttft_p50 \
               + '<span class="stat">均速度: %s</span>' % speed_avg \
               + '<span class="stat">P70 速度: %s</span>' % speed_p70 \
               + '</div>' \
               + '<table><tr><th>#</th><th>用例ID</th><th>状态</th><th>TTFT</th><th>耗时</th><th>速度</th><th>Tokens</th></tr>' \
               + table_body \
               + '</table></div>'

    def export_json(self, raw_data, run_id=None):
        fp = os.path.join(
            self.output_dir,
            "test-data-%s.json" % (run_id or datetime.now().strftime("%Y%m%d_%H%M%S"))
        )
        with open(fp, "w", encoding="utf-8") as f:
            json.dump(raw_data, f, ensure_ascii=False, indent=2)
        return fp
